### ISSUE TITLE
Thank you very much for your excellent work, I would like to know how the entity_context.pkl file for each dataset is generated

### ISSUE THREAD

**Issue by bananices0** [sonniki/image-captioning-with-external-knowledge#1]
For example, if I switch to my own dataset, how do I get this entity_context.pkl file?

**Comment by sonniki** [comment]
Thank you for the interest in my work!

For custom datasets, entity contexts have to be built from scratch, and the specifics of how it is done heavily depend on the kinds of entities that exist in the dataset captions and the features they can be encoded with. The trick is to identify which "real world" entities are present in the captions of your dataset, and which of their characteristics would provide the best (most informative) representation for them. E.g., consider how in this repo in the "geo-aware" setup the entities are geographic locations with features like distance, azimuth, etc., and in the "news-knowledge-aware" setup the entities are named entities from newspaper articles with features like the number of occurrences in the text, whether it occurs in the headline of the article, etc. 

The scripts in the repo assume the following structure of the `entity_context.pkl` file: a Python dictionary with the unique image ids as keys and the contexts themselves as values. The contexts are in a Pandas dataframe format, where the rows are entities and the columns are features the entities are encoded with.
Once you have the data in this format, the functions you might need to modify are `prepare_context()` in `utils.py`, to make sure that the custom features of your entities are processed correctly, and `get_data_for_image()` in `create_input_files.py`, to make sure the call to `prepare_context()` in this function has appropriate column names and ranges from which the random feature values would be selected.
